FROM postgres:12
EXPOSE 5432
ENV POSTGRES_PASSWORD 1234
ENV POSTGRES_USER test
ENV POSTGRES_DB testdb
ENV POSTGRES_INITDB_ARGS -E=UTF8
ENV PGDATA=/var/lib/postgresql/data/pgdata
#COPY blog.csv /var/lib/postgresql/data/pgdata
#COPY init-db.sql /docker-entrypoint-initdb.d/



